### ISSUE TITLE
getting millet working

### ISSUE THREAD

**Issue by azdavis** [fabjan/shiny-octo-spork#1]
from discussion on https://github.com/azdavis/millet/issues/51

your original post:

> I have a similar issue (I believe) with the Lua library in [LunarML](https://github.com/minoki/LunarML). I tried setting the SML_LIB path variable but Millet cannot find the `Lua` structure as defined in the LunarML extra basis library.
>
> I realize LunarML might not be the most used SML implementation out there, and not high on the priorities for Millet, but I shared a small repository reproducing my problem here on the odd chance someone has time to look at it eventually: https://github.com/fabjan/shiny-octo-spork. The README explains what I have tried, to bridge this gap between LunarML and Millet. It might all be a problem I am causing, not being a Standard ML pro at all.

---

i took a look and it seems like you need to add some more path variables for lunar ml, like

```toml
TARGET_LANG = { value = "lua" }
DELIMITED_CONTINUATIONS = { value = "none" }
```

after this, millet does sort of figure out what `Lua` is but not fully, since there are still hundreds of errors.

---

from poking around a bit more it doesn't seem the easiest to fix. i think because lunarml's libs define the standard basis (as well as some extra stuff like Lua) at least three not great things are happening:

1. since millet already has its own defs of the standard basis built in, millet's built-in defs and the defs from lunarml's sources clash/override.
2. since the standard basis defines things not available in 'regular' standard ml like overloaded operators, lunarml's sources likely do some special 'magic' to define those things that millet doesn't know how to deal with.
3. more generally, since lunarml appears to implement things outside the scope of the '97 definition of standard ml and the handful of successor ml features that millet supports, millet can't analyze lunarml's source files that use those extra features without trouble.

i think your approach with using the functor + lua sig is the most likely to work. i would suggest:

1. write a minimal signature for the stuff you need from lua in your own signature file.
2. generally use functors, signatures, and structures to thread things together without actually needing the real `Lua` struct itself yet.
4. have all that (but NOT any lunarml imports) in one mlb file
5. point millet at that mlb file ONLY. that way millet won't choke trying to analyze lunarml
6. then have another mlb that imports that first mlb (that millet is pointed at), as well as the real `Lua` from lunarml, and a 'main' sml file
7. in the 'main' sml file, apply all the functors to the necessary structures (like Lua from lunarml) and run your program.

it seems like you already tried basically that, though i'm not sure why that's not working. from the error from lunarml, it seems like lunarml's own `Lua` does not conform to the signature that the documentation said it should? that doesn't seem right.

**Comment by fabjan** [comment]
Hey, thanks a bunch for the input, and the thorough investigation.

That day I made that comment was basically the first time I wrote a functor at all, and my knowledge of how to combine signatures and structures are a bit limited. I can surely read up a bit more and see that I really exhausted my options. Given you believe that approach could work I am motivated to try it further.

I'll share progress in this repo if I make any. And will follow up with LunarML if there is something that can be fixed on that side (e.g. in https://github.com/minoki/LunarML/issues/9).

**Comment by fabjan** [comment]
Progress: it works.

The problem (well one problem) seems to be that using the `--luajit` flag to the lunarml compiler makes it implement a smaller subset of Lua, and the sig file I created by extracting from the LunarML repo includes things that are not in it. The hint that made it click for me was that I saw some things commented out in the sig with the note "Lua 5.4". Instead of scraping them off one by one I started with a minimal sig.

As per your suggestion I also "inverted" the relation between my two MLB files for Millet and for building. So instead of trying to solve it by creating some wrapper for Millet to know about everything, Millet only checks the stuff that doesn't know about Lua.

The outermost MLB just glues together Lua and the game. I get syntax hilighting from Millet, but nothing more. This is fine, those files will not be changing a lot and I can probably refactor stuff to make this part smaller.
